CREATE TABLE Table_01 (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  descripcion VARCHAR(100) NOT NULL,
  nombres VARCHAR(50) NOT NULL,
  apellidos VARCHAR(50) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE Table_02 (
  id INTEGER UNSIGNED NOT NULL AUTO_INCREMENT,
  Table_01_id INTEGER UNSIGNED NOT NULL,
  ciudad VARCHAR(50) NOT NULL,
  direccion VARCHAR(50) NOT NULL,
  fechar_hora DATETIME NOT NULL,
  fecha INTEGER UNSIGNED NOT NULL,
  telefono INTEGER UNSIGNED NOT NULL,
  valor_pago FLOAT NOT NULL,
  email VARCHAR(50) NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY (Table_02) REFERENCES Table_01 (id)
);


